name = "tg"
main = "worker/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "7638d434c539b37415fea565654cc614"

# 配置静态资源
[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true
binding = "ASSETS"

[[d1_databases]]
# Replace database_id with your actual D1 database id before deploy
binding = "DB"
database_name = "nodecrypt-db"
database_id = "8b918b0d-ad7b-4904-ad93-7cac4040a1cc"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
